/* Automatically generated by tools/system_libs.py */
#define __EMSCRIPTEN_MAJOR__ 5
#define __EMSCRIPTEN_MINOR__ 0
#define __EMSCRIPTEN_TINY__ 7

// Legacy mixed-case macros:
#define __EMSCRIPTEN_major__ __EMSCRIPTEN_MAJOR__
#define __EMSCRIPTEN_minor__ __EMSCRIPTEN_MINOR__
#define __EMSCRIPTEN_tiny__ __EMSCRIPTEN_TINY__
#pragma clang deprecated(__EMSCRIPTEN_major__, "Use __EMSCRIPTEN_MAJOR__ instead")
#pragma clang deprecated(__EMSCRIPTEN_minor__, "Use __EMSCRIPTEN_MINOR__ instead")
#pragma clang deprecated(__EMSCRIPTEN_tiny__, "Use __EMSCRIPTEN_TINY__ instead")
