name: CI
on:
  push:
  pull_request:
env:
  EM_VERSION: 4.0.8
  EM_CACHE_FOLDER: 'emsdk-cache'
jobs:
  build:
    name: WASM Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository and submodules
        uses: actions/checkout@v7
        with:
          submodules: recursive
          fetch-tags: true
          fetch-depth: 0
      - name: Set up cache
        uses: actions/cache@v5
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Set up emscripten
        uses: emscripten-core/setup-emsdk@v16
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      - name: Configure emscripten builds
        run: emcmake cmake -B build -G Ninja
      - name: Build RGBDS and binjgb
        run: cmake --build build
      - name: Install node dependencies
        run: npm ci
      - name: Build with Vite
        run: npm run build
      - name: Deploy to GitHub Pages
        # Do not run this unless *pushing* to `master`.
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./www
